--: ''
jpa:
    hibernate:
        ddl-auto: create
    properties:
        hibernate:
            format_sql: true
logging:
    level:
        org:
            hibernate:
                SQL: debug
server:
    port: 8080
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
            force-response: true
servlet:
    servlet:
        register-default-servlet: true
spring:
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        password: '@dminPassword1234!'
        url: jdbc:oracle:thin:@gsdb1_high?TNS_ADMIN=./src/main/resources/wallet
        username: ADMIN
    jpa:
        properties:
            hibernate:
                show_sql: true
                use_Sql_comments: true
    main:
        allow-bean-definition-overriding: true
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    thymeleaf:
        prefix: classpath:/static/
